In [1]:
import numpy as np

import tensorflow as tf
from tensorflow.keras import layers

In [2]:
tf.__version__

'2.5.0'

In [3]:
x = tf.constant([[1., 2.], [4., 4.]])
x = tf.reshape(x, (1, 2, 2, 1))
tf.reduce_mean(x, axis=[2, 1])

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[2.75]], dtype=float32)>

In [4]:
x = np.ones((1, 3, 3))
x[0, :, 0] = 5
global_avg = layers.GlobalAveragePooling1D()
global_avg(x)

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[5., 1., 1.]], dtype=float32)>

In [5]:
x = np.ones((1, 4, 3))
x[0, :, 0] = 5
avg = layers.AveragePooling1D(pool_size=2)
avg(x)

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[5., 1., 1.],
        [5., 1., 1.]]], dtype=float32)>

In [6]:
for x in [64] * 3 + [128] * 4:
    print(x)

64
64
64
128
128
128
128


In [9]:
[1, 2, 3] + [2]

[1, 2, 3, 2]